export default {
  required: "required",
  max: "max length",
  min: "minimum",
  char: "characters",

  name: "Name",
  phone: "Phone",
  wechat: "Wechat",
  email: "Email",
  province: "Province",
  city: "City",
  description: "Description",
  address: "Address",
  supplier: "Supplier",
  type: "Type",
  code: "Code",
  costPrice: "Cost price",
  sellPrice: "Sell price",
  qtyInStock: "Quantity",
  image: "Select Image",
  isPrivate: "Personal Item?",
  archived: "Archive item?",
};
